version: "3.8"

services:
  db:
    ports:
      - "5432:5432"
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=docker_db

  backend:
    build:
      dockerfile: Dockerfile
    container_name: app_container
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/docker_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - db